import { Inter } from 'next/font/google';
import './globals.css';
import { AppBar, Toolbar, Typography, Button, Container, Box } from '@mui/material';
import Link from 'next/link';
import React from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Inventory Tracker',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
      <Box
      width="100vw"
      height="100vh"
      sx={{ 
        backgroundImage: 'url(/images/pantry-background.jpg)', // Add your background image
        backgroundSize: 'cover',
        backgroundPosition: 'center',
      }}
    >
      {/* Header with Menu */}
      <AppBar position="static" sx={{ bgcolor: '#967969' }}>
        <Toolbar>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            Pantry Tracker
          </Typography>
          <Button color="inherit" component={Link} href="/">Home</Button>
        </Toolbar>
      </AppBar>
        <main>
          <Container>
            {children}
          </Container>
        </main>
        </Box>
      
      </body>
    </html>
  );
}




