import { Inter } from 'next/font/google';
import './globals.css';
import { AppBar, Toolbar, Typography, Button, Component, Box, pageProps } from '@mui/material';
import Link from 'next/link';
import React from 'react';
import Head from 'next/head';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import theme from '@/app/theme';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Inventory Tracker',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" type="image/x-icon" /> {/* Use your favicon path */}
      </Head>
        <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
        
        {/* <Box
        width="100vw"
        height="100vh"
        sx={{ 
          backgroundImage: 'url(/images/pantry-background.jpg)', // Add your background image
          backgroundSize: 'cover',
          backgroundPosition: 'center',
        }}
      > */}
        {/* Header with Menu */}
        <AppBar position="static" sx={{ bgcolor: '#967969' }}>
          <Toolbar>
            <Typography variant="h6" sx={{ flexGrow: 1 }}>
              Pantry Tracker
            </Typography>
            <Button color="inherit" component={Link} href="/">Home</Button>
          </Toolbar>
        </AppBar>
          <main>
              {children}
          </main>
          {/* </Box> */}
          </ThemeProvider>
        </body>
    </html>
  );
}




